import './about_us.css';
import './additional.css';
import './article_details.css';
import './feedback_list.css';
import './movie_details.css';
import './movies.css';
import './news.css';
import './sign_up.css';
import './style.css';
