# Generated by Django 4.2.1 on 2023-09-21 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='film', to='cinema.film'),
        ),
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hall', to='cinema.hall'),
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='cinema.category'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['film'], name='cinema_sess_film_id_867235_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['id', 'slug'], name='cinema_film_id_f889bc_idx'),
        ),
    ]
