version: '3.7'
services:
  db:
    container_name: postgre
    image: postgres:16.1
    restart: always
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql@16.1/data
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql@16.1/data
volumes:
  db: